version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./local/homeassistant:/config
      - ./local/homeassistant/configuration.yaml:/config/configuration.yaml
      - ./local/homeassistant/automation.yaml:/config/automation.yaml
      - ./local/homeassistant/customize.yaml:/config/customize.yaml
      - ./local/homeassistant/group.yaml:/config/group.yaml
      - ./local/homeassistant/scene.yaml:/config/scene.yaml
      - ./local/homeassistant/script.yaml:/config/script.yaml
      - ./local/homeassistant/sensor.yaml:/config/sensor.yaml
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - TZ=America/New_York
    restart: always
  mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./local/mosquitto:/mosquitto    
      - ./local/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./local/mosquitto/log:/mosquitto/log
      - ./local/mosquitto/certs:/mosquitto/certs
    restart: always
  openzwave:
    container_name: openzwave
    image: openzwave/ozwdaemon:latest
    network_mode: host
    volumes:
      - ./local/openzwave:/opt/ozw/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    env_file:
      - ./local/creds/secrets.env
    environment:
      - MQTT_SERVER=localhost
      - MQTT_PORT=8883
      - MQTT_TLS=true
      - USB_PATH=/dev/ttyUSB0
    security_opt:
      - seccomp:unconfined
    restart: always 

# notes
# volume symlink only works with files not directories
