version: '3'
services:

  homeassistant:
    container_name: home-assistant
    depends_on:
      - "mosquitto"
      - "zwavejs2mqtt"
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./local/homeassistant:/config
      - ./local/homeassistant/configuration.yaml:/config/configuration.yaml
      - ./local/homeassistant/automation.yaml:/config/automation.yaml
      - ./local/homeassistant/customize.yaml:/config/customize.yaml
      - ./local/homeassistant/group.yaml:/config/group.yaml
      - ./local/homeassistant/scene.yaml:/config/scene.yaml
      - ./local/homeassistant/script.yaml:/config/script.yaml
      - ./local/homeassistant/sensor.yaml:/config/sensor.yaml
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - TZ=America/New_York
    restart: always

  mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./local/mosquitto:/mosquitto    
      - ./local/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./local/mosquitto/log:/mosquitto/log
      - ./local/mosquitto/certs:/mosquitto/certs
    restart: always

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    network_mode: host
    tty: true
    stop_signal: SIGINT
    devices:
      - '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_314002FD-if00-port0:/dev/zwave'
    volumes:
      - ./local/zwavejs2mqtt:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
    restart: always

# notes
# volume symlink only works with files not directories
