import random

words = [
    "You look amazing!",
    "That meal you made was delicious!",
    "I'm so lucky to be with you.",
    "I love that outfit on you!",
    "I love how smart you are.",
    "I love how funny you are.",
    "I love how kind you are.",
    "I love how organized you are.",
    "You make my heart sing.",
    "You make everything better.",
    "I couldn't do this without you.",
    "I'm so glad you're in my life.",
    "You're so fun.",
    "You're so exciting.",
    "You're so hilarious.",
    "I trust you.",
    "I believe in you.",
    "I need you.",
    "I know I can always count on you.",
    "You're so fun to be with.",
    "You're so special to me.",
    "I feel so grateful that I get to be with you.",
    "I love our life together.",
    "Thank you for listening.",
    "I missed you.",
    "I love how you get me.",
    "I'm so happy to see you.",
    "You're the best.",
    "No one makes me laugh as much as as you do.",
    "No one makes me feel as happy as much as as you do.",
    "No one makes me feel as beautiful as much as as you do.",
    "You're such a good partner.",
    "You help me feel like I can do anything.",
    "When I'm with you, I'm a better person.",
    "You handled that like a pro.",
    "I value your judgement.",
    "I'm so proud of you.",
    "Your support means the world to me.",
    "I love how you see the world.",
    "Thank you for being a wonderful listener.",
    "You broaden my perspective.",
    "I hope you know how much you mean to me.",
    "Being with you makes me so happy!",
    "Being with you makes me so inspired!",
    "Being with you makes me so joyful]!",
    "I love your smile.",
    "I love your laugh.",
    "I love your eyes.",
    "I love your way of seeing things.",
    "Thank you for sharing your opinions with me.",
    "I love that I can be myself with you.",
    "Thank you for being honest with me.",
    "You're so thoughtful.",
    "You're so kind.",
    "You're so sexy.",
    "My life is more meaningful with you in it.",
    "You rocked that situation.",
    "I love how well you understand me.",
    "You're my best friend.",
    "You're one of my favorite people to be around.",
    "You take such good care of me.",
    "You always know the right thing to say.",
    "You help me so much.",
    "Thank you for being in my life.",
    "We work so well together.",
    "You're an inspiration!",
    "I love you.",
    "You are my sunshine.",
    "I'm sorry I hurt you.",
    "I love that you did this for me.",
    "Your being here makes everything better.",
    "It must be so tough to deal with this. How can I help?",
    "You are amazing.",
    "You inspire me.",
    "Thank you for taking the time to do this with me.",
    "You did that! Go you!",
    "I learn so much from you.",
    "I love your ideas.",
    "You do so much for the people in your life.",
    "I'm proud to be your partner.",
    "I have total confidence in you.",
    "I love how you make time for me.",
    "I respect you.",
    "I love being with you.",
    "You know how to make me laugh!",
    "You know how to make me happy!",
    "I feel safe with you.",
    "You have the best sense of humor.",
    "I love when we do something special together.",
    "I'll always be here for you.",
    "You make everything more fun.",
    "You're such a good lover.",
    "Thanks for seeing what I need.",
    "We make a great team.",
    "Hello, gorgeous.",
    "Hey there, sexy.",
    "I trust your judgement.",
    "Your opinion means so much to me.",
    "You're so considerate.",
    "You really are the best.",
    "You make so many things possible.",
    "I love your company.",
    "You're a dream come true.",
    "You're one in a million.",
    "Do you know how much I love you?",
    "Things feel easier with you here.",
    "You help me in so many ways.",
    "I don't know what I'd do without you.",
    "I feel so lucky to have you in my life.",
    "You've totally got this!",
    "Your perspective is invaluable.",
    "Wow! That was incredible!",
    "Your dinners are the best.",
    "Your backrubs are the best.",
    "Your ideas are the best.",
    "I love how your mind works.",
    "Want to come with me?",
    "I love how you see things.",
    "Good thinking!",
    "I appreciate you.",
    "What a good idea!",
    "Thank you for loving me."
]

i = random.randint(0, len(words) -1)
print(words[i])