# alarm
- alias: alarm_set_home
  trigger:
    - platform: state
      entity_id: person.benjamin_weiner
      to: "home"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: alarm_set_away
  trigger:
    - platform: state
      entity_id: person.benjamin_weiner
      to: "not_home"
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: alarm_away_trigger
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_open
      to: "on"
    - platform: state
      entity_id: lock.front_door
      to: "unlocked"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

- alias: alarm_notification
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    - service: notify.mail
      data:
        title: "Home: Alarm Triggered"
        message: "Alarm Triggered at {{ states('sensor.date_time') }}"
    - service: notify.sms
      data:
        title: ""
        message: "Home Alarm Triggered at {{ states('sensor.date_time') }}"

# bedroom lights
- alias: bedroom_lights_on
  trigger:
    platform: state
    entity_id: light.bedroom_light
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: switch.bedroom_floor_lamp

- alias: bedroom_lights_off
  trigger:
    platform: state
    entity_id: light.bedroom_light
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: switch.bedroom_floor_lamp

# entryway button
- alias: trigger_hello
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      command: button_single
  action:
    - scene: scene.hello
    - service: script.tts_greeting

- alias: trigger_goodbye
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      command: button_double
  action:
    - service: script.tts_departure
    - scene: scene.goodbye

# closet light
- alias: closet_light_on
  trigger:
    platform: state
    entity_id: binary_sensor.closet_open_sensor
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: light.closet_light

- alias: closet_light_off
  trigger:
    platform: state
    entity_id: binary_sensor.closet_open_sensor
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: light.closet_light

# printer
- alias: printer_on
  trigger:
    platform: time
    at: '09:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.printer_switch

- alias: printer_off
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.printer_switch

# coffee
- alias: coffee_on
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.coffee_switch

- alias: coffee_off_morning
  trigger:
    platform: time
    at: '10:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_switch

- alias: coffee_off_night
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_switch

# water sensors
- alias: kitchen_water
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_water_sensor
    to: "on"
  action:
    - service: notify.mail
      data:
        title: "Home: Water Detected"
        message: "Water Detected in Kitchen"
    - service: notify.sms
      data:
        title: ""
        message: "Water Detected in Kitchen"

- alias: laundry_water
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_water_sensor
    to: "on"
  action:
    - service: notify.mail
      data:
        title: "Home: Water Detected"
        message: "Water Detected in Laundry"
    - service: notify.sms
      data:
        title: ""
        message: "Water Detected in Laundry"

# living room light
- alias: living_room_light_toggle
  trigger:
    platform: mqtt
    topic: "remote/living_room_light"
    payload: "toggle"
  action:
    service: homeassistant.toggle
    entity_id: light.living_room_light

# clear tts cache
- alias: clear_tts
  trigger:
    platform: time
    at: "00:00:00"
  action:
    service: tts.clear_cache
