# alarm
- alias: alarm_set_home
  trigger:
    - platform: state
      entity_id: person.ben
      to: "home"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: alarm_set_away
  trigger:
    - platform: state
      entity_id: person.ben
      to: "not_home"
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: alarm_away_trigger
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_open
      to: "on"
    - platform: state
      entity_id: lock.front_door
      to: "unlocked"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

- alias: alarm_notification
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    - service: notify.mail
      data:
        title: "Home: Alarm Triggered"
        message: "Alarm Triggered at {{ states('sensor.date_time') }}"
    - service: notify.sms
      data:
        title: ""
        message: "Home Alarm Triggered at {{ states('sensor.date_time') }}"

# water sensors
- alias: kitchen_water
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_water_sensor
    to: "on"
  action:
    - service: notify.mail
      data:
        title: "Home: Water Detected"
        message: "Water Detected in Kitchen"
    - service: notify.sms
      data:
        title: ""
        message: "Water Detected in Kitchen"

- alias: laundry_water
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_water_sensor
    to: "on"
  action:
    - service: notify.mail
      data:
        title: "Home: Water Detected"
        message: "Water Detected in Laundry"
    - service: notify.sms
      data:
        title: ""
        message: "Water Detected in Laundry"

- alias: water_leak
  trigger:
    platform: state
    entity_id: sensor.daily_water
  condition:
    - condition: state
      entity_id: person.ben
      state: "not_home"
    - condition: state
      entity_id: person.ivy
      state: "not_home"
  action:
    - service: notify.mail
      data:
        title: "Home: Water Detected"
        message: "Water Meter Active"
    - service: notify.sms
      data:
        title: ""
        message: "Water Meter Active"

# bedroom lights
- alias: bedroom_lights_on
  trigger:
    platform: state
    entity_id: light.bedroom_light
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: switch.bedroom_floor_lamp

- alias: bedroom_lights_off
  trigger:
    platform: state
    entity_id: light.bedroom_light
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: switch.bedroom_floor_lamp

# entryway button
- alias: trigger_hello
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      command: button_single
  action:
    - scene: scene.hello
    - service: script.turn_on
      target:
        entity_id: script.tts_sonos
      data:
        variables:
          tts_entity: media_player.living_room
          message: >
            {% set t = now().strftime("%I:%M %p") %}        
            {% set d = now().strftime("%A, %B %-d") %}
            {% set h = now().strftime("%H")|int %}
            {% if h < 12 %} Good Morning. 
            {% elif h < 18 %} Good Afternoon. 
            {% else %} Good Evening.
            {% endif %}
            The time is, 
            {{ t }}, on 
            {{ d }},
            it is currently {{states('weather.home')}} and 
            {{state_attr('weather.home', 'temperature')}} degrees.

- alias: trigger_goodbye
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      command: button_double
  action:
    - scene: scene.goodbye
    - service: script.turn_on
      target:
        entity_id: script.tts_sonos
      data:
        variables:
          tts_entity: media_player.living_room
          message: Goodbye. Get  some!

# closet light
- alias: closet_light_on
  trigger:
    platform: state
    entity_id: binary_sensor.closet_open_sensor
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: light.closet_light

- alias: closet_light_off
  trigger:
    platform: state
    entity_id: binary_sensor.closet_open_sensor
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: light.closet_light

# printer
- alias: printer_on
  trigger:
    platform: time
    at: '09:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.printer_switch

- alias: printer_off
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.printer_switch

# coffee
- alias: coffee_on
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.coffee_switch

- alias: coffee_off_morning
  trigger:
    platform: time
    at: '10:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_switch

- alias: coffee_off_night
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_switch

# holiday lights
- alias: holiday_on_am
  trigger:
    platform: time
    at: '08:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.holiday_light

- alias: holiday_off_am
  trigger:
    platform: time
    at: '10:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.holiday_light


- alias: holiday_on_pm
  trigger:
    platform: time
    at: '16:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.holiday_light

- alias: holiday_off_pm
  trigger:
    platform: time
    at: '10:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.holiday_light

# mqtt remote
- alias: living_room_light_toggle
  trigger:
    platform: mqtt
    topic: "remote/living_room_light"
    payload: "toggle"
  action:
    service: homeassistant.toggle
    entity_id: light.living_room_light

- alias: living_room_light_dim
  trigger:
    platform: mqtt
    topic: "remote/living_room_light"
    payload: "dim"
  action:
    choose:
      # if > 254 (max 255)
      conditions:
        condition: numeric_state
        entity_id: light.living_room_light
        attribute: brightness
        above: 254
      sequence:
        data:
          entity_id: light.living_room_light
          brightness_pct: 25
        service: light.turn_on
    default:
      data:
        entity_id: light.living_room_light
        brightness_pct: 100
      service: light.turn_on

- alias: tts_wiki_today
  trigger:
    platform: mqtt
    topic: "remote/tts"
    payload: "wiki_today"
  action:
    - service: homeassistant.update_entity
      data:
        entity_id: sensor.wiki_today
    - service: script.turn_on
      target:
        entity_id: script.tts_sonos
      data:
        variables:
          tts_entity: media_player.living_room
          message: "{{ states( 'sensor.wiki_today' ) }}"
      
- alias: tts_woa
  trigger:
    platform: mqtt
    topic: "remote/tts"
    payload: "woa"
  action:
    - service: homeassistant.update_entity
      data:
        entity_id: sensor.woa
    - service: script.turn_on
      target:
        entity_id: script.tts_sonos
      data:
        variables:
          tts_entity: media_player.living_room
          message: "{{ states( 'sensor.woa' ) }}"

# clear tts cache
- alias: clear_tts
  trigger:
    platform: time
    at: "00:00:00"
  action:
    service: tts.clear_cache
