# home assistant configuration
homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

# integrations 
default_config:

logger:
  default: info
  logs:
    homeassistant.components.mqtt: warning
    homeassistant.components.zha: warning

# http:
#   ssl_certificate: /config/certs/server.crt
#   ssl_key: /config/certs/server.key

tts:
  - platform: google_translate

alarm_control_panel:
  - platform: manual
    name: Home Alarm

mqtt:
  broker: localhost
  port: 8883
  username: mqtt
  password: !secret mqtt_password
  certificate: /config/certs/ca.crt
  client_key: /config/certs/client.key
  client_cert: /config/certs/client.crt

emulated_hue:
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - light
    - switch

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

august:
  login_method: !secret august_login_method
  username: !secret august_username
  password: !secret august_password

# includes
sensor: !include sensor.yaml
group: !include group.yaml
scene: !include scene.yaml
automation: !include automation.yaml
script: !include script.yaml
