# home assistant configuration
homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/New_York
  currency: USD
  country: US
  customize: !include customize.yaml

# integrations 
default_config:

lovelace:
  mode: storage
  dashboards:
    lovelace-home:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards/default.yaml

frontend:
  extra_module_url:
    - /local/layout-card.js
    - /local/card-mod.js

recorder:
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.date_time_iso

logger:
  default: info
  logs:
    homeassistant.components.mqtt: warning
    homeassistant.components.zha: warning

# http:
#   ssl_certificate: /config/certs/server.crt
#   ssl_key: /config/certs/server.key

tts:
  - platform: google_translate

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    delay_time: 60
    arming_time: 30
    disarm_after_trigger: true

notify:
  - name: mail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: !secret notify_mail_username
    password: !secret notify_mail_password
    sender: !secret notify_mail_sender
    recipient: !secret notify_mail_recipient
    sender_name: Home Notification
  - name: sms
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: !secret notify_mail_username
    password: !secret notify_mail_password
    sender: !secret notify_mail_sender
    recipient: !secret notify_sms_recipient
    sender_name: Home Notification

# mqtt:
#   broker: localhost
#   port: 8883
#   username: mqtt
#   password: !secret mqtt_password
#   certificate: /config/certs/ca.crt
#   client_key: /config/certs/client.key
#   client_cert: /config/certs/client.crt

mqtt:
  sensor:
  - name: "Water Meter"
    state_topic: "util/water"
    unit_of_measurement: "gal"
    device_class: water
    state_class: total_increasing
    force_update: true

emulated_hue:
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - light
    - switch

homekit:
  - name: HASS Bridge
    port: 21063
    filter:
      include_domains:
        - light
        - switch

# nest:
#   client_id: !secret nest_client_id
#   client_secret: !secret nest_client_secret
#   project_id: !secret nest_project_id
#   subscriber_id: !secret nest_subscriber_id

# august:
#   login_method: !secret august_login_method
#   username: !secret august_username
#   password: !secret august_password

utility_meter:
  daily_water:
    name: Daily Water
    source: sensor.water_meter
    cycle: daily
    delta_values: true

# includes
sensor: !include sensor.yaml
command_line: !include command-line.yaml
group: !include group.yaml
scene: !include scene.yaml
automation: !include automation.yaml
script: !include script.yaml
