light.bedroom_light:
  friendly_name: Bedroom Light
switch.bedroom_floor_lamp:
  friendly_name: Bedroom Floor Lamp
light.headboard_light:
  friendly_name: Headboard Light
light.bathroom_light:
  friendly_name: Bathroom Light
light.closet_light:
  friendly_name: Closet Light
light.counter_light:
  friendly_name: Counter Light
light.entryway_light:
  friendly_name: Entryway Light
light.hallway_light:
  friendly_name: Hallway Light
light.living_room_light:
  friendly_name: Living Room Light
light.kitchen_light:
  friendly_name: Kitchen Light
light.bar_light:
  friendly_name: Bar Light

light.printer_switch:
  friendly_name: Printer
switch.coffee_switch:
  friendly_name: Coffee

binary_sensor.kitchen_water_sensor:
    friendly_name: Kitchen Water Sensor
binary_sensor.laundry_water_sensor:
  friendly_name: Laundry Water Sensor

binary_sensor.closet_open_sensor:
  friendly_name: Closet Open Sensor
binary_sensor.frontdoor_open_sensor:
  friendly_name: Front Door Open Sensor

sensor.bedroom_temperature:
  friendly_name: Bedroom Temperature
sensor.entryway_temperature:
  friendly_name: Entryway Temperature
sensor.hallway_temperature:
  friendly_name: Hallway Temperature
sensor.kitchen_temperature:
  friendly_name: Kitchen Temperature
sensor.laundry_temperature:
  friendly_name: Laundry Temperature

cover.patio_blinds:
  friendly_name: Patio Blinds
  