tts_greeting:
  alias: TTS Greeting
  sequence:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room
      volume_level: 0.3
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room
      message: >
        {% set t = now().strftime("%I:%M %p") %}        
        {% set d = now().strftime("%A, %B %-d") %}
        {% set h = now().strftime("%H")|int %}
        {% if h < 12 %} Good Morning. 
        {% elif h < 18 %} Good Afternoon. 
        {% else %} Good Evening.
        {% endif %}
        The time is, 
        {{ t }}, on 
        {{ d }},
        it is currently {{states('weather.home')}} and 
        {{state_attr('weather.home', 'temperature')}} degrees.
  mode: single

tts_departure:
  alias: TTS Departure
  sequence:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room
      volume_level: 0.3
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room
      message: >
        Goodbye. Get  some!
  mode: single
