tts_sonos:
  alias: TTS and Resume (sonos)
  sequence:
    - service: sonos.snapshot
      data:
        entity_id: '{{ tts_entity }}'
        with_group: true
    - service: media_player.volume_set
      data:
        entity_id: '{{ tts_entity }}'
        volume_level: 0.35
    - service: tts.google_translate_say
      data:
        entity_id: '{{ tts_entity }}'
        message: '{{ message }}'
    - delay: 1
    - alias: Wait until media player is paused
      wait_template: '{{ is_state(tts_entity, ''paused'') }}'
    - service: media_player.volume_set
      data:
        entity_id: '{{ tts_entity }}'
        volume_level: '{{ mediaplayer_volume_level }}'
    - service: sonos.restore
      data:
        entity_id: '{{ tts_entity }}'
        with_group: true
  icon: mdi:text-to-speech
  variables:
    mediaplayer_volume_level: '{{ state_attr(tts_entity,''volume_level'') }}'
  mode: single
